### ISSUE TITLE
Turkish Transifex strings - pull problem?

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/i18n#2]
Turkish team says that their Transifex strings, even though translated and revised, do not show up in the Deeds. Might there be a pull problem?

**Comment by RCEurope1** [comment]
in concreto: They mention this page ... http://creativecommons.org/licenses/?lang=tr ... as one where they made changes to the Turkish text which do not show.

**Comment by mattl** [comment]
Hey, I just fixed another problem with transifex and a bunch of translations came down the pipe. Can you see if this is improved any?

**Comment by RCEurope1** [comment]
they say it shows up now correctly, seems fixed
